### ISSUE TITLE
Add system notification support

### ISSUE THREAD

**Issue by yunusem** [yunusem/PardusImageWriter#12]
Notify user over system notifications about how writing process ended.

**Comment by eminfedar** [comment]
QSystemTrayIcon class can display native system notifications with [QSystemTrayIcon::showMessage](http://doc.qt.io/qt-5/qsystemtrayicon.html#showMessage)

But if you don't want to add a tray icon you can use this little hack:
```
QSystemTrayIcon* trayIcon = new QSystemTrayIcon(this);

trayIcon->show(); // Show the icon
trayIcon->showMessage("TEST","MSG"); // Display The Message
trayIcon->hide(); // Hide again the icon
```

**Comment by yunusem** [comment]
I have already tried it, but it has rediculius windows xp like appereance. 
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdsxyu4yRkcIQGymiiXw5tjSt_x1yCUbDcJK_DzBQNaQE8n4Ge

What i want is that general system notification support api that we can use as crossplatform.

But thanx for your comment.

**Comment by eminfedar** [comment]
**I've tried it on Ubuntu 16.04 LTS and the result is:**
![notif](https://user-images.githubusercontent.com/14258668/35470306-0c42521a-0358-11e8-9653-d466b9183682.png)

I think also in Windows, it will uses Notification Center notifications too. What are you searching for?

**Comment by yunusem** [comment]
The problem is XFCE then, maybe an exceptional case for linux we can call notifyd as subprocess. In xfce desktop environment the notification is just like what i shared in previous comment although xfce has nice notification system like gnome.
