### ISSUE TITLE
What is the minimum Qt Version to build/run?

### ISSUE THREAD

**Issue by gokhanettin** [yunusem/PardusImageWriter#15]
I cannot build the project on Ubuntu 16.04. It seems the project requires higher Qt version.
We had better update `README.md` with the required Qt version.

Here is what get on my system.
```
$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
```

There are several ways we can further improve the project.
- Build with CMake. You can make sure the system has all the dependencies with correct versions -even before compilation starts- using `find_package` command.
- Use travis, appveyor, CircularCI etc... continuously build the project for every PR for all systems you are targeting, like GNU/Linux, MacOS, and Windows.

**Comment by yunusem** [comment]
There was only 1 decleration in main.cpp that requires Qt version 5.6 and above, the others fine with 5.5 and above.
