### ISSUE TITLE
Where are the binaries for Windows?

### ISSUE THREAD

**Issue by mrkaban** [yunusem/PardusImageWriter#19]
There are screenshots of the program on Windows, but in the releases tab there is no assembly for Windows.

**Comment by yilmazmuhammed** [comment]
You can download from the pardus forum post.
https://forum.pardus.org.tr/t/kalip-dosyasi-yazici-program/3667/58?u=edge35

**Comment by yunusem** [comment]
https://github.com/yunusem/pardus-imagewriter/releases/download/upstream%2F0.1.6/piw.exe
